version: 2
jobs:
  build:
    docker:
      - image: "circleci/openjdk:8-jdk"

    working_directory: ~/webapp

    environment:

      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - run: mvn dependency:go-offline
       
      - run: mvn package
      - run: mkdir /tmp/artifacts
      - run: mv target/sysfoo.war /tmp/artifacts/sysfoo.war
      
      - store_artifacts:
          path: /tmp/artifacts
          destination: /tmp/artifacts/sysfoo.war
